=== JuliaKazm/OnlineBookShop/OnlineBookShop/src/main/resources/xml xsd/Orders.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="orders">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="order" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="orders_id" type="xs:int"/>
                            <xs:element name="customer_id" type="xs:int"/>
                            <xs:element name="order_date" type="xs:date"/>
                            <xs:element name="order_status" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JuliaKazm/OnlineBookShop/OnlineBookShop/src/main/resources/xml xsd/Ordres.xml
<?xml version="1.0" encoding="UTF-8"?>
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Orders.xsd">
    <order>
        <orders_id>1</orders_id>
        <customer_id>123</customer_id>
        <order_date>2023-05-30</order_date>
        <order_status>Processing</order_status>
    </order>
    <order>
        <orders_id>2</orders_id>
        <customer_id>456</customer_id>
        <order_date>2023-06-01</order_date>
        <order_status>Shipped</order_status>
    </order>
</orders>
